name: 'Fork Test Action'
description: 'A test action for fork-sync e2e testing'
inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
runs:
  using: 'node20'
  main: 'index.js'
